Suggestions for Dynamic Transforms
Spartwo/StockCombatAI pull request #4
Opened 2022-12-27 22:16 UTC by Halbann

- Create dynamic control points when needed.
- Calculate propulsion debug line once.
- Make RCS list optional in GetFireVector.
- Fix docking port separation.
- Separator spelling change.
- Simplify FindDecoupler params.
- Miscellaneous tweaks & comment changes.

2022-12-27 23:04 UTC, Spartwo commented on Source/KerbalCombatSystems/MissileGuidance.cs
> +            // Get a probe core and align its reference transform with the propulsion vector.
lah dee daa mr literate

2022-12-27 23:26 UTC, Spartwo requested changes

2022-12-27 23:26 UTC, Spartwo commented on Source/KerbalCombatSystems/MissileGuidance.cs
> -        private List<ModuleRCSFX> rcsList;
move the rcs list storage back to here so that it can be recalled during flight to update

2022-12-27 23:26 UTC, Spartwo commented on Source/KerbalCombatSystems/Utils.cs
> -            //check the parent itself
//check the parent itself

keep this in, more documentation is always positive

2022-12-27 23:45 UTC, Spartwo commented on Source/KerbalCombatSystems/MissileGuidance.cs
>          private ModuleWeaponController controller;
```suggestion
        private ModuleWeaponController controller;
        private List<ModuleRCSFX> rcsThrusters;
```

2022-12-27 23:48 UTC, Spartwo commented on Source/KerbalCombatSystems/MissileGuidance.cs
>          private ModuleWeaponController controller;
move the rcs list storage back to here so that it can be recalled during flight to update

2022-12-27 23:48 UTC, Spartwo commented on Source/KerbalCombatSystems/MissileGuidance.cs
> +            List<ModuleRCSFX> rcsThrusters = vessel.FindPartModulesImplementing<ModuleRCSFX>();
```suggestion
            rcsThrusters = vessel.FindPartModulesImplementing<ModuleRCSFX>();
```

2022-12-28 00:11 UTC, Spartwo commented on Source/KerbalCombatSystems/Utils.cs
>          {
```suggestion
        {
            if (type == null) type = "Default";

```

2022-12-28 00:11 UTC, Spartwo commented on Source/KerbalCombatSystems/Utils.cs
>                  if (module == null) continue;
```suggestion
                if (module == null) continue;
                //"" is shorthand for ignoring the type requirement and firing any decoupler
```

2022-12-28 00:11 UTC, Spartwo commented on Source/KerbalCombatSystems/Utils.cs
>          {
```suggestion
        {
            if (type == null) type = "Default";

```

2022-12-28 00:11 UTC, Spartwo commented on Source/KerbalCombatSystems/Utils.cs
>              childParts.Insert(0, root);
```suggestion
            childParts.Insert(0, root); //check the parent itself
```

2022-12-28 00:11 UTC, Spartwo commented on Source/KerbalCombatSystems/Utils.cs
>                  if (module == null) continue;
```suggestion
                if (module == null) continue;
                //"" is shorthand for ignoring the type requirement and firing any decoupler
```

2022-12-28 00:11 UTC, Spartwo commented on Source/KerbalCombatSystems/Utils.cs
> +            // Create a new transform named dynamic.
```suggestion
      {
           ControlPoint dynamic = commander.GetControlPoint("dynamic");
            // Check for an already extant dynamic control point
            if (dynamic == null)
            {
                // Create a new transform named dynamic.
                GameObject tc = new GameObject("dynamic");
                Transform transform = tc.transform;
                transform.SetParent(commander.transform);
                transform.position = commander.transform.position;

                // Create a new control point with the transform.
                dynamic = new ControlPoint("dynamic", "Dynamic", transform, Vector3.zero);

                // Add the control point to the command module and set it as active.
                commander.controlPoints.Add("dynamic", dynamic);
                commander.SetControlPoint("dynamic");
            }

            // Orient the control point towards direction (finger) with perpendicular as the up vector (thumb).
            Vector3 perpendicular = Vector3.ProjectOnPlane(commander.transform.forward, direction);
            dynamic.transform.rotation = Quaternion.LookRotation(perpendicular, direction); // VAB orientation.
        }
```

2022-12-28 00:11 UTC, Spartwo commented on Source/KerbalCombatSystems/Utils.cs
> +            dynamic.transform.rotation = Quaternion.LookRotation(perpendicular, direction); // VAB orientation.
```suggestion
           
```

2022-12-28 00:11 UTC, Spartwo commented on Source/KerbalCombatSystems/Utils.cs
> +            dynamic.transform.rotation = Quaternion.LookRotation(perpendicular, direction); // VAB orientation.
```suggestion
```

2022-12-28 00:11 UTC, Spartwo commented on Source/KerbalCombatSystems/Utils.cs
> +            commander.SetControlPoint("dynamic");
```suggestion
```

2022-12-28 00:11 UTC, Spartwo commented on Source/KerbalCombatSystems/Utils.cs
> +            transform.position = commander.transform.position;
```suggestion
```

2022-12-28 00:15 UTC, Halbann commented on Source/KerbalCombatSystems/Utils.cs
>          {
This should probably be indented.

2022-12-28 00:17 UTC, Halbann commented on Source/KerbalCombatSystems/Utils.cs
>          {
Indent please. Also this doesn't really make sense but sure if you want it to be troll proof.

2022-12-28 00:18 UTC, Spartwo commented on Source/KerbalCombatSystems/Utils.cs
>          {
this is the indentation that the browser provided, I will do it on desktop in WIP branch

2022-12-28 00:23 UTC, Spartwo commented on Source/KerbalCombatSystems/Utils.cs
>          {
these are indented

2022-12-28 01:13 UTC, merged